=== KinkyKay/Java_Tooling/Summary XML/Continent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="continent">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="continentName" type="xsd:string"/>
                <xsd:element name="country" maxOccurs="12">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="countryName" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="countryLeader" maxOccurs="12">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="countryLeaderName"/>
                            <xsd:element name="countryLeaderCountry"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:key name="oneCountry">
            <xsd:selector xpath="country"/>
            <xsd:field xpath="countryName"/>
        </xsd:key>
        <xsd:keyref name="countryRef" refer="oneCountry">
            <xsd:selector xpath="countryLeader"/>
            <xsd:field xpath="countryLeaderCountry"/>
        </xsd:keyref>
    </xsd:element>
</xsd:schema>

=== KinkyKay/Java_Tooling/Summary XML/continent.xml
<?xml version="1.0" encoding="UTF-8"?>
<continent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="Continent.xsd">
    <continentName>Europe</continentName>
    <country>
        <countryName>Belgium</countryName>
    </country>
    <country>
        <countryName>The Netherlands</countryName>
    </country>
    <country>
        <countryName>Luxemburg</countryName>
    </country>
    <countryLeader>
        <countryLeaderName>Willem II</countryLeaderName>
        <countryLeaderCountry>The Netherlands</countryLeaderCountry>
    </countryLeader>
    <countryLeader>
        <countryLeaderName>Albert II</countryLeaderName>
        <countryLeaderCountry>Belgium</countryLeaderCountry>
    </countryLeader>
    <countryLeader>
        <countryLeaderName>Boudewijn</countryLeaderName>
        <countryLeaderCountry>Belgium</countryLeaderCountry>
    </countryLeader>
</continent>
