=== KinkyKay/Java_Tooling/Summary XML/country.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="country" type="xsd:string">
        <xsd:complexType><xsd:sequence>
            <xsd:element name="countryName" type="xsd:string"/>
            <xsd:element name="continent"/>
            <xsd:element name="countryLeader">
                <xsd:complexType><xsd:sequence>
                    <xsd:element ref="title"/>
                        <xsd:choice>
                        <xsd:element ref="name"/>
                        <xsd:sequence>
                            <xsd:element name="firstName" type="xsd:string"/>
                            <xsd:element name="lastName" type="xsd:string"/>
                        </xsd:sequence>
                        </xsd:choice>
                    <xsd:element ref="since"/>
                </xsd:sequence></xsd:complexType>
            </xsd:element>
        </xsd:sequence></xsd:complexType>
    </xsd:element>
    <xsd:element name="title"/>
    <xsd:element name="name"/>
    <xsd:element name="since"/>
</xsd:schema>

=== KinkyKay/Java_Tooling/summaryXML/country.xml
<?xml version="1.0" encoding="UTF-8"?>
<country
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="country.xsd">
    <countryName>Belgium</countryName>
    <continent>Europe</continent>
    <countryLeader>
        <title>King</title>
        <name>Philippe/Filip</name>
        <since>2013-07-21</since>
    </countryLeader>
    <countryLeader>
        <title>Primeminister</title>
        <firstName>Charles</firstName>
        <lastName>Michel</lastName>
        <since>2014-10-11</since>
    </countryLeader>
</country>
