=== KinkyKay/Java_Tooling/Training/xml/CompanyListZipcode.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  targetNamespace="www.abis.be"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:abis="www.abis.be" elementFormDefault="qualified"
>
<xs:simpleType name="postcodeType">
    <xs:restriction base="xs:string">
        <xs:pattern value="[1-9]{1}[0-9]{3}"/>
        <xs:pattern value="[1-9]{1}[0-9]{3} [A-Z]{2}"/>
    </xs:restriction>
</xs:simpleType>
<xs:element name="CompanyList">
<xs:complexType>
    <xs:sequence>
        <xs:element name="Company" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="CompanyName" type="xs:string"/>
                    <xs:element name="CompanyAddress">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute name="postcode" type="abis:postcodeType"/>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="PersonList">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="Person" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="Name">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="FirstName" type="xs:string"/>
                                                        <xs:element name="LastName" type="xs:string"/>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="Function" type="xs:string"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>
</xs:element>
        </xs:schema>

=== KinkyKay/Java_Tooling/training/xml/CompanyListZipcode.xml
<?xml version="1.0" encoding="UTF-8" ?>
<CompanyList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="CompanyListZipcode.xsd"
             xmlns="www.abis.be" xsi:schemaLocation="www.abis.be" >
    <Company>
        <CompanyName/>
        <CompanyAddress/>
        <PersonList>
            <Person>
                <Name>
                    <FirstName>K.</FirstName>
                    <LastName>LOOSE</LastName>
                </Name>
                <Function>CONSULTANT</Function>
            </Person>
        </PersonList>
    </Company>
    <Company>
        <CompanyName>ABIS N.V.</CompanyName>
        <CompanyAddress postcode="3000">LEUVEN</CompanyAddress>
        <PersonList>
            <Person>
                <Name>
                    <FirstName>JAN</FirstName>
                    <LastName>SMITHS</LastName>
                </Name>
                <Function>TRAINING CONSULT</Function>
            </Person>
            <Person>
                <Name>
                    <FirstName>ANN</FirstName>
                    <LastName>DE KEYSER</LastName>
                </Name>
                <Function>PROGRAMMER</Function>
            </Person>
            <Person>
                <Name>
                    <FirstName>PETER</FirstName>
                    <LastName>TAVERNIER</LastName>
                </Name>
                <Function>PROGRAMMER</Function>
            </Person>
        </PersonList>
    </Company>
    <Company>
        <CompanyName>COMPUTRAIN</CompanyName>
        <CompanyAddress postcode="2000 AC">ROTTERDAM</CompanyAddress>
        <PersonList>
            <Person>
                <Name>
                    <FirstName>GERT</FirstName>
                    <LastName>VAN HEIJKOOP</LastName>
                </Name>
                <Function>ANALYST</Function>
            </Person>
            <Person>
                <Name>
                    <FirstName>RUUD</FirstName>
                    <LastName>NIEHOF</LastName>
                </Name>
                <Function>EDP-MANAGER</Function>
            </Person>
        </PersonList>
    </Company>
</CompanyList>
