=== KinkyKay/Java_Tooling/training/xml/VenetianBlindCompanyList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="CompanyType">
		<xs:sequence>
			<xs:element ref="CompanyName"/>
			<xs:element ref="CompanyAddress"/>
			<xs:element name="PersonList" type="PersonListType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="CompanyAddress" type="xs:string"/>
	<xs:element name="CompanyList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Company" type="CompanyType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CompanyName" type="xs:string"/>
	<xs:element name="FirstName" type="xs:string"/>
	<xs:element name="Function" type="xs:string"/>
	<xs:element name="LastName" type="xs:string"/>
	<xs:complexType name="NameType">
		<xs:sequence>
			<xs:element ref="FirstName"/>
			<xs:element ref="LastName"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PersonType">
		<xs:sequence>
			<xs:element name="Name" type="NameType"/>
			<xs:element ref="Function"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PersonListType">
		<xs:sequence>
			<xs:element name="Person" type="PersonType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== KinkyKay/Java_Tooling/Training/xml/VenetianBlindCompanyList.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CompanyList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="VenetianBlindcompanyList.xsd">
	<Company>
		<CompanyName/>
		<CompanyAddress/>
		<PersonList>
			<Person>
				<Name>
					<FirstName>K.</FirstName>
					<LastName>LOOSE</LastName>
				</Name>
				<Function>CONSULTANT</Function>
			</Person>
		</PersonList>
	</Company>
	<Company>
		<CompanyName>ABIS N.V.</CompanyName>
		<CompanyAddress>LEUVEN</CompanyAddress>
		<PersonList>
			<Person>
				<Name>
					<FirstName>JAN</FirstName>
					<LastName>SMITHS</LastName>
				</Name>
				<Function>TRAINING CONSULT</Function>
			</Person>
			<Person>
				<Name>
					<FirstName>ANN</FirstName>
					<LastName>DE KEYSER</LastName>
				</Name>
				<Function>PROGRAMMER</Function>
			</Person>
			<Person>
				<Name>
					<FirstName>PETER</FirstName>
					<LastName>TAVERNIER</LastName>
				</Name>
				<Function>PROGRAMMER</Function>
			</Person>
		</PersonList>
	</Company>
	<Company>
		<CompanyName>COMPUTRAIN</CompanyName>
		<CompanyAddress>ROTTERDAM</CompanyAddress>
		<PersonList>
			<Person>
				<Name>
					<FirstName>GERT</FirstName>
					<LastName>VAN HEIJKOOP</LastName>
				</Name>
				<Function>ANALYST</Function>
			</Person>
			<Person>
				<Name>
					<FirstName>RUUD</FirstName>
					<LastName>NIEHOF</LastName>
				</Name>
				<Function>EDP-MANAGER</Function>
			</Person>
		</PersonList>
	</Company>
</CompanyList>
