=== KinkyKay/Java_Tooling/src/main/java/excercises/PersonList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="PersonList">
        <xs:complexType><xs:sequence>
            <xs:element name="Person" maxOccurs="unbounded">
                    <xs:complexType><xs:sequence>
                        <xs:element name="Name">
                            <xs:complexType><xs:sequence>
                                <xs:element name="FirstName"/>
                                <xs:element name="LastName"/>
                            </xs:sequence></xs:complexType>
                        </xs:element>
                        <xs:element name="Function"/>
                        <xs:element name="Company" minOccurs="0">
                            <xs:complexType><xs:sequence>
                                <xs:element name="CompanyName"/>
                                <xs:element name="CompanyAddress"/>
                            </xs:sequence></xs:complexType>
                        </xs:element>
                    </xs:sequence></xs:complexType>
            </xs:element>
        </xs:sequence></xs:complexType>
    </xs:element>
</xs:schema>

=== KinkyKay/Java_Tooling/training/xml/Personlist.xml
<?xml version="1.0" encoding="UTF-8" ?>
<PersonList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="PersonList.xsd">
    <Person>
        <Name>
            <FirstName>JAN</FirstName>
            <LastName>SMITHS</LastName>
        </Name>
        <Function>TRAINING CONSULT</Function>
        <Company>
            <CompanyName>ABIS Training &amp; Consulting</CompanyName>
            <CompanyAddress>LEUVEN</CompanyAddress>
        </Company>
    </Person>
    <Person>
        <Name>
            <FirstName>
                Gert
            </FirstName>
            <LastName>Van Heijkoop</LastName>
        </Name>
    </Person>
    <Person>
        <Name>
            <FirstName>PETER</FirstName>
            <LastName>TAVERNIER</LastName>
        </Name>
        <Function>PROGRAMMER</Function>
        <Company>
            <CompanyName>ABIS N.V.</CompanyName>
            <CompanyAddress>LEUVEN</CompanyAddress>
        </Company>
    </Person>
    <Person>
        <Name>

            <FirstName>Philip</FirstName>
            <LastName>Benoit</LastName>
        </Name>
        <Function>tester</Function>
    </Person>
</PersonList>

=== KinkyKay/Java_Tooling/src/main/java/excercises/PersonList.xml
<?xml version="1.0" encoding="UTF-8" ?>
<PersonList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="PersonList.xsd">
    <Person>
        <Name>
            <FirstName>JAN</FirstName>
            <LastName>SMITHS</LastName>
        </Name>
        <Function>TRAINING CONSULT</Function>
        <Company>
            <CompanyName>ABIS Training &amp; Consulting</CompanyName>
            <CompanyAddress>LEUVEN</CompanyAddress>
        </Company>
    </Person>
    <Person>
        <Name>
            <FirstName>PETER</FirstName>
            <LastName>TAVERNIER</LastName>
        </Name>
        <Function>PROGRAMMER</Function>
        <Company>
            <CompanyName>ABIS N.V.</CompanyName>
            <CompanyAddress>LEUVEN</CompanyAddress>
        </Company>
    </Person>
    <Person>
        <Name>
            <FirstName>ANN</FirstName>
            <LastName>DE KEYSER</LastName>
        </Name>
        <Function>PROGRAMMER</Function>
        <Company>
            <CompanyName>ABIS N.V.</CompanyName>
            <CompanyAddress>LEUVEN</CompanyAddress>
        </Company>
    </Person>
    <Person>
        <Name>
            <FirstName>RUUD</FirstName>
            <LastName>NIEHOF</LastName>
        </Name>
        <Function>EDP-MANAGER</Function>
        <Company>
            <CompanyName>COMPUTRAIN</CompanyName>
            <CompanyAddress>ROTTERDAM</CompanyAddress>
        </Company>
    </Person>
    <Person>
        <Name>
            <FirstName>GERT</FirstName>
            <LastName>VAN HEIJKOOP</LastName>
        </Name>
        <Function>ANALYST</Function>
        <Company>
            <CompanyName>COMPUTRAIN</CompanyName>
            <CompanyAddress>ROTTERDAM</CompanyAddress>
        </Company>
    </Person>
    <Person>
        <Name>
            <FirstName>MARIA</FirstName>
            <LastName>PEREZ</LastName>
        </Name>
        <Function>MANAGER</Function>
        <Company>
            <CompanyName>DATAWISHES N.V.</CompanyName>
            <CompanyAddress>BRUSSEL</CompanyAddress>
        </Company>
    </Person>
    <Person>
        <Name>
            <FirstName>F.</FirstName>
            <LastName>LIVIER</LastName>
        </Name>
        <Function>ANALYST</Function>
        <Company>
            <CompanyName>DATAWISHES N.V.</CompanyName>
            <CompanyAddress>BRUSSEL</CompanyAddress>
        </Company>
    </Person>
    <Person>
        <Name>
            <FirstName>K.</FirstName>
            <LastName>LOOSE</LastName>
        </Name>
        <Function>CONSULTANT</Function>
        <Company>
            <CompanyName>-</CompanyName>
            <CompanyAddress>-</CompanyAddress>
        </Company>
    </Person>
    <Person>
        <Name>
            <FirstName>PHILIP</FirstName>
            <LastName>BENOIT</LastName>
        </Name>
        <Function>SOFTWARE ENGINEER</Function>
        <Company>
            <CompanyName>LOC COMPUTER CORP</CompanyName>
            <CompanyAddress>BRUSSEL</CompanyAddress>
        </Company>
    </Person>
</PersonList>
